const CONFIG={
 APP_NAME:"GALAXY EMPIRE",
 VERSION:"4.1.0",
 STARTING_NOVA:500,
 NOVA_DECIMALS:0,
 GAME_TICK_MS:16,
 DISTANCE_NOVA_RATE:1,
 STARTING_ROCKET:"explorer",
 BASE_MAX_ACTIVE_ROCKETS:1,
 ROCKET_SPEED_BASE:8,
 DISPLAY_SPEED_FACTOR:1,
 SIMULATION_SPEED:6,
 GRAVITY_SCALE:0.00018,
 ARRIVAL_DISTANCE:7,
 ROCKET_FUEL_START:100,
 FUEL_CONSUMPTION:0.12,
 MAX_TRAIL_POINTS:360
};