const CONFIG = {
    APP_NAME: "GALAXY EMPIRE",
    VERSION: "2.1.0",

    STARTING_NOVA: 0,

    NOVA_DECIMALS: 2,

    GAME_TICK_MS: 16,
    AUTO_SAVE_INTERVAL_SEC: 30,
    OFFLINE_MAX_HOURS: 12,

    STARTING_ROCKET: "explorer",

    MAX_TECH_LEVEL: 50,
    LEADERBOARD_LIMIT: 50,

    // Monnaie unique : 1 km = 1 NOVA de base
    DISTANCE_NOVA_RATE: 1.0,

    SPAWN_BASE_INTERVAL: 1.15,
    SPAWN_MIN_INTERVAL: 0.38,

    DIFFICULTY_PER_KM: 0.08,

    SCROLL_BASE: 180,

    SPEED_START_MULTIPLIER: 1.0,
    SPEED_MAX_MULTIPLIER: 3.3,
    SPEED_RAMP_SECONDS: 300,
    SPEED_RAMP_POWER: 1.6,

    DISTANCE_PER_SECOND: 0.18,

    HIT_IFRAMES: 0.45
};