let player,simulation;
const $=id=>document.getElementById(id);
function init(){player=SaveSystem.load();simulation=new SpaceSimulation($("spaceCanvas"),player);bindTools();bindPanel();bindLaunch();renderAll();setInterval(()=>{const r=getRocket(player.currentRocket);Economy.addNova(player,Economy.getNovaPerMinute(player,r)/60);SaveSystem.save(player);renderHud()},1000);setInterval(renderAll,500)}
function bindTools(){document.querySelectorAll(".tool-button").forEach(b=>b.addEventListener("click",()=>openPanel(b.dataset.panel)))}
function bindPanel(){bindMapControls();$("closePanel").addEventListener("click",closePanel);$("closeSelection").addEventListener("click",()=> $("selectionCard").classList.add("hidden"));$("spaceCanvas").addEventListener("click",e=>{const r=$("spaceCanvas").getBoundingClientRect(),b=simulation.handleClick(e.clientX-r.left,e.clientY-r.top);if(b)showSelection(b)});$("launchAngle").addEventListener("input",()=>{simulation.setAimAngle($("launchAngle").value);$("angleValue").textContent=($("launchAngle").value>=0?"+":"")+$("launchAngle").value+"°"})}
function openPanel(id){$("sidePanel").classList.remove("hidden");document.querySelectorAll(".panel-section").forEach(s=>s.classList.toggle("active",s.id==="panel-"+id));document.querySelectorAll(".tool-button").forEach(b=>b.classList.toggle("active",b.dataset.panel===id));$("panelTitle").textContent={launch:"LANCEMENT",planets:"MONDES",technologies:"TECHNOLOGIES",fleet:"FLOTTE"}[id]||id.toUpperCase();renderAll()}
function closePanel(){$("sidePanel").classList.add("hidden");document.querySelectorAll(".tool-button").forEach(b=>b.classList.remove("active"))}
function bindMapControls(){const canvas=$("spaceCanvas");const zoomLabel=$("zoomValue");const updateZoom=()=>{if(zoomLabel)zoomLabel.textContent=Math.round(simulation.camera.zoom*100)+"%"};let drag=false,lastX=0,lastY=0;canvas.addEventListener("wheel",e=>{e.preventDefault();const r=canvas.getBoundingClientRect();simulation.handleWheel(e.clientX-r.left,e.clientY-r.top,e.deltaY);updateZoom()},{passive:false});canvas.addEventListener("pointerdown",e=>{if(e.button!==0)return;drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!drag)return;simulation.pan(e.clientX-lastX,e.clientY-lastY);lastX=e.clientX;lastY=e.clientY});canvas.addEventListener("pointerup",e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener("pointercancel",()=>drag=false);$("zoomIn").addEventListener("click",()=>{simulation.camera.zoom=Math.min(4,simulation.camera.zoom*1.25);updateZoom()});$("zoomOut").addEventListener("click",()=>{simulation.camera.zoom=Math.max(.18,simulation.camera.zoom*.8);updateZoom()});$("resetView").addEventListener("click",()=>{simulation.camera.x=0;simulation.camera.y=0;simulation.camera.zoom=1;updateZoom()});updateZoom()}
function bindLaunch(){$("launchOrigin").addEventListener("change",()=>{simulation.setAimOrigin($("launchOrigin").value);renderLaunch()});$("launchDestination").addEventListener("change",renderLaunch);$("launchButton").addEventListener("click",()=>{const res=simulation.launch($("launchOrigin").value,$("launchDestination").value,Number($("launchAngle").value));$("launchMessage").textContent=res.ok?"🚀 Fusée lancée. Navigation automatique activée.":"⚠️ "+res.message;renderAll()})}
function renderLaunch(){const bodies=simulation.bodies.filter(b=>b.base||b.type==="planet"||b.type==="moon"),oldO=$("launchOrigin").value||"earth";$("launchOrigin").innerHTML=bodies.filter(b=>b.base).map(b=>"<option value='"+b.id+"'>"+b.name+"</option>").join("");$("launchOrigin").value=bodies.some(b=>b.id===oldO&&b.base)?oldO:"earth";const origin=$("launchOrigin").value,oldD=$("launchDestination").value||"mars";$("launchDestination").innerHTML=bodies.filter(b=>b.id!==origin).map(b=>"<option value='"+b.id+"'>"+b.name+"</option>").join("");$("launchDestination").value=bodies.some(b=>b.id===oldD&&b.id!==origin)?oldD:(bodies.find(b=>b.id!==origin)?.id||"mars");const rocket=getRocket(player.currentRocket);$("launchRocketName").textContent=rocket.name;$("launchSpeed").textContent=Math.round(CONFIG.ROCKET_SPEED_BASE*simulation.speedMultiplier()*CONFIG.DISPLAY_SPEED_FACTOR)+" km/s";$("launchFuel").textContent="100 %";$("launchButton").disabled=simulation.rockets.filter(r=>r.active).length>=simulation.maxRockets()}
function renderTech(){const box=$("technologyList");box.innerHTML=TECHNOLOGY_ORDER.map(id=>{const t=getTechnology(id),l=player.technologies[id]||0,cost=getTechnologyCost(id,l),max=l>=t.maxLevel;return"<div class='tech-card'><div class='tech-icon'>"+t.icon+"</div><div><h3>"+t.name+"</h3><p>"+t.description+"</p><div class='tech-level'>Niveau "+l+"/"+t.maxLevel+"</div></div><button data-tech='"+id+"' "+(max||player.nova<cost?"disabled":"")+">"+(max?"MAX":cost.toLocaleString("fr-FR")+" ✦")+"</button></div>"}).join("");box.querySelectorAll("[data-tech]").forEach(b=>b.addEventListener("click",()=>buyTech(b.dataset.tech)))}
function buyTech(id){const l=player.technologies[id]||0,cost=getTechnologyCost(id,l);if(!Number.isFinite(cost)||player.nova<cost)return;player.nova-=cost;player.technologies[id]=l+1;SaveSystem.save(player);renderAll()}
function renderPlanets(){$("planetsList").innerHTML=simulation.bodies.filter(b=>b.base||b.type==="planet").map(b=>"<div class='object-card'><div><h3>"+b.name+"</h3><p>Base active · masse "+b.mass+"</p></div><span class='state'>"+simulation.rockets.filter(r=>r.origin===b.id&&r.active).length+" 🚀</span></div>").join("")}
function renderFleet(){const list=$("fleetList"),active=simulation.rockets.filter(r=>r.active);$("fleetCount").textContent=active.length+" / "+simulation.maxRockets();list.innerHTML=active.length?active.map(r=>{const o=simulation.bodies.find(b=>b.id===r.origin),d=simulation.bodies.find(b=>b.id===r.destination);return"<div class='object-card'><div><h3>🚀 "+(o?.name||"?")+" → "+(d?.name||"?")+"</h3><p>Navigation automatique · carburant "+Math.max(0,Math.round(r.fuel))+"%</p></div><span class='state'>EN VOL</span></div>"}).join(""):"<div class='empty'>Aucune fusée en vol.</div>"}
function showSelection(b){$("selectionCard").classList.remove("hidden");$("selectionType").textContent=b.type==="star"?"ÉTOILE":b.type==="moon"?"LUNE":"PLANÈTE";$("selectionName").textContent=b.name;$("selectionInfo").textContent=b.base?"Base interplanétaire. Peut envoyer des fusées vers les autres corps.":"Corps céleste influençant les trajectoires par sa gravité."}
function renderHud(){const r=getRocket(player.currentRocket);$("nova").textContent=Math.floor(player.nova).toLocaleString("fr-FR");$("novaPerMinute").textContent=Economy.getNovaPerMinute(player,r).toFixed(1).replace(".",",");$("activeRockets").textContent=simulation.rockets.filter(r=>r.active).length;$("maxRockets").textContent=simulation.maxRockets();$("simTime").textContent=formatTime(simulation.time);$("simStatus").textContent=simulation.rockets.some(r=>r.active)?"Navigation autonome":"Simulation active"}
function renderAll(){renderHud();renderLaunch();renderTech();renderPlanets();renderFleet()}
function formatTime(sec){const days=Math.floor(sec/86400),hours=Math.floor(sec/3600)%24;return days+" j "+String(hours).padStart(2,"0")+" h"}
addEventListener("load",init);